name: snowpark_041
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.8
  - pip
  - pip:
    - './include/snowflake_snowpark_python-0.4.1-py3-none-any.whl[pandas]'
    - pytorch-tabnet
    - matplotlib
    - seaborn
    - rexmex
    - ipykernel
